project_id = "wspspxjabyjnpwbkfssd"

[functions.uploadpost-create-profile]
verify_jwt = false

[functions.uploadpost-get-accounts]
verify_jwt = false

[functions.uploadpost-delete-profile]
verify_jwt = false

[functions.uploadpost-connect-account]
verify_jwt = false

[functions.uploadpost-refresh-accounts]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
